javadoc:
	javadoc	-sourcepath $(SRCDIR) -d $(VRDIR)/doc -use -splitIndex -windowtitle $(WINDOWTITLE) -header $(HEADER) -bottom $(BOTTOM) -group $(GROUPCORE) -J-Xmx180m braincraft

WINDOWTITLE = 'Braincraft Documentation'
HEADER = 'Braincraft'
BOTTOM = '2011-2012 Chris Donahue'
GROUPCORE = 'braincraft'
SRCDIR = ./
VRDIR = ../v1.0
